from __future__ import annotations

import math, re, sys, unicodedata
from pathlib import Path
from urllib.parse import urlparse, parse_qs

import pandas as pd
import geopandas as gpd

try:
    import pyarrow.parquet as pq
except Exception:
    pq = None

STOPA_OUT = Path(r"C:\AkerSync-AkerAccess\work\akerminne_streetview_stopa")
TRUTH = STOPA_OUT / "selected_truth.csv"
MINNE_ROOT = Path(r"C:\AkerSync-Minne\data\derived\akerminne_v1a\skane\municipalities")
CURRENT_GPKG = Path(r"C:\AkerSyncRaw\jv_skane_2025\arslager_skifte_skane_2025.gpkg")
RAW_ROOTS = [Path(r"C:\AkerSyncRaw"), Path(r"C:\AkerSync-Minne")]
OUT = STOPA_OUT / "diag_geometry_v0e"
OUT.mkdir(parents=True, exist_ok=True)

def norm(x):
    s = "" if x is None else str(x)
    s = unicodedata.normalize("NFKD", s).encode("ascii","ignore").decode("ascii").lower()
    return re.sub(r"[^a-z0-9]+","_",s).strip("_")

def canon(v):
    s = "" if pd.isna(v) else str(v).strip()
    if re.fullmatch(r"\d+\.0", s): s=s[:-2]
    p=[x.strip() for x in s.split("|")]
    if len(p)>=3 and re.fullmatch(r"20\d{2}",p[0]): s="|".join(p[1:])
    return s

def choose(cols, exact=(), token_sets=()):
    nm={c:norm(c) for c in cols}
    for e in exact:
        en=norm(e)
        for c,n in nm.items():
            if n==en: return c
    for toks in token_sets:
        tt=[norm(t) for t in toks]
        hits=[c for c,n in nm.items() if all(t in n for t in tt)]
        if hits:
            return sorted(hits,key=lambda c:(len(nm[c]),nm[c]))[0]
    return None

def field_col(cols):
    return choose(cols,
        exact=("current_field_id","field_id","m0_field_id","skifte_id","skiftes_id","skiftesid","skifteid"),
        token_sets=(("current","field","id"),("field","id"),("skifte","id")))

def year_col(cols):
    return choose(cols, exact=("year","ar","år","crop_year","odlingsar"),
                  token_sets=(("year",),("odlings","ar")))

def parse_pano(url):
    # URL generated by STOPA: ...?api=1&map_action=pano&viewpoint=lat,lon
    try:
        q=parse_qs(urlparse(str(url)).query)
        v=q.get("viewpoint",[None])[0]
        if v:
            a,b=v.split(",")
            return float(a),float(b)
    except Exception:
        pass
    return None,None

if not TRUTH.exists():
    raise SystemExit(f"FEL: Hittar inte {TRUTH}. Kör STOPA först.")

truth=pd.read_csv(TRUTH)
truth["field_id"]=truth["field_id"].map(canon)
truth["year"]=pd.to_numeric(truth["year"],errors="coerce").astype("Int64")
truth[["pano_lat","pano_lon"]]=truth["streetview_url"].apply(lambda u: pd.Series(parse_pano(u)))
print(f"Diagnosfall: {len(truth)} ({', '.join(truth.case_id.astype(str))})")
print("Målår:", truth["year"].value_counts().sort_index().to_dict())

# ---------- A. Inspect ÅkerMinne internal parquet evidence ----------
detail_frames=[]
schema_rows=[]
target_ids=set(truth["field_id"].dropna().astype(str))
target_years=set(int(x) for x in truth["year"].dropna())

parquets=[]
for m in sorted(set(truth["municipality"].astype(str).str.lower())):
    hits=[p for p in MINNE_ROOT.rglob("*.parquet") if m in norm(str(p.parent))]
    parquets.extend(hits)
parquets=sorted(set(parquets))
print(f"\nÅkerMinne parquetfiler att inspektera: {len(parquets)}")

for p in parquets:
    try:
        cols = list(pq.ParquetFile(p).schema.names) if pq else list(pd.read_parquet(p).columns)
    except Exception as e:
        schema_rows.append({"file":str(p),"error":type(e).__name__})
        continue
    fc=field_col(cols); yc=year_col(cols)
    keycols=[]
    for c in cols:
        n=norm(c)
        if any(t in n for t in (
            "field","skifte","block","year","odlings","crop","groda","raps",
            "overlap","cover","coverage","share","ratio","fraction","frac",
            "area","domin","match","class","source","parent","child","histor"
        )):
            keycols.append(c)
    keycols=list(dict.fromkeys(keycols))
    schema_rows.append({"file":str(p),"field_col":fc,"year_col":yc,
                        "n_cols":len(cols),"key_columns":" | ".join(keycols)})
    if not fc:
        continue
    readcols=list(dict.fromkeys([fc]+([yc] if yc else [])+keycols))
    try:
        # Municipality files are manageable; selective column read avoids unnecessary payload.
        d=pd.read_parquet(p, columns=readcols)
    except Exception:
        continue
    ids=d[fc].map(canon)
    mask=ids.isin(target_ids)
    if yc:
        yy=pd.to_numeric(d[yc],errors="coerce")
        mask &= yy.isin(target_years)
    d=d.loc[mask].copy()
    if d.empty:
        continue
    d.insert(0,"__source_file",str(p))
    d.insert(1,"__canonical_field_id",ids.loc[mask].values)
    detail_frames.append(d)

pd.DataFrame(schema_rows).to_csv(OUT/"akerminne_file_inventory.csv",index=False,encoding="utf-8-sig")
if detail_frames:
    details=pd.concat(detail_frames,ignore_index=True,sort=False)
    details.to_csv(OUT/"akerminne_matching_rows.csv",index=False,encoding="utf-8-sig")
    print(f"ÅkerMinne interna matchrader hittade: {len(details)} -> akerminne_matching_rows.csv")
else:
    details=pd.DataFrame()
    print("ÅkerMinne: inga extra matchrader hittades utöver summary via generell schema-sökning.")

# ---------- B. Current 2025 geometry ----------
if not CURRENT_GPKG.exists():
    raise SystemExit(f"FEL: Hittar inte 2025-geometrin {CURRENT_GPKG}")
cur=gpd.read_file(CURRENT_GPKG)
bc=choose(cur.columns, exact=("blockid","block_id"), token_sets=(("block","id"),))
sc=choose(cur.columns, exact=("skiftesbeteckning","skiftebeteckning"), token_sets=(("skifte","beteckning"),))
if not bc or not sc:
    raise SystemExit("FEL: kan inte skapa BLOCKID|SKIFTESBETECKNING i 2025-GPKG.")
cur["field_id"]=cur[bc].map(canon)+"|"+cur[sc].map(canon)
cur=cur[cur["field_id"].isin(target_ids)].copy()
if cur.crs is None:
    raise SystemExit("FEL: 2025-GPKG saknar CRS.")
cur=cur.to_crs(3006)
print(f"2025-geometrier: {len(cur)}/{truth.field_id.nunique()} unika valda fält.")

# ---------- C. Locate historical field geometry ----------
def score_candidate(p:Path, year:int):
    n=norm(str(p))
    score=0
    if "skifte" in n: score+=10
    if str(year) in n: score+=20
    if "arslager" in n: score+=5
    if "skane" in n: score+=4
    if "2025" in n and year!=2025: score-=20
    return score

def candidate_files(year:int):
    c=[]
    for root in RAW_ROOTS:
        if not root.exists(): continue
        # First pass: filenames/path explicitly mentioning target year.
        for p in root.rglob("*.gpkg"):
            if str(year) in str(p) and "skifte" in norm(str(p)):
                c.append(p)
        for p in root.rglob("*.parquet"):
            if str(year) in str(p) and "skifte" in norm(str(p)):
                c.append(p)
    return sorted(set(c), key=lambda p:score_candidate(p,year), reverse=True)

def read_hist_candidate(path:Path, year:int, bbox):
    try:
        if path.suffix.lower()==".gpkg":
            g=gpd.read_file(path, bbox=bbox)
        else:
            g=gpd.read_parquet(path)
            if g.crs and bbox:
                # bbox filter manually only after CRS conversion if needed
                pass
        if g.empty or "geometry" not in g.columns or g.crs is None:
            return None
        yc=year_col(g.columns)
        if yc:
            yy=pd.to_numeric(g[yc],errors="coerce")
            vals=set(int(v) for v in yy.dropna().unique()[:30])
            if year in vals or len(vals)>1:
                g=g[yy==year].copy()
        return g
    except Exception:
        return None

geometry_rows=[]
source_rows=[]
for year in sorted(target_years):
    case_y=truth[truth["year"]==year]
    cur_y=cur[cur["field_id"].isin(set(case_y["field_id"]))].copy()
    if cur_y.empty: continue
    # bbox transformed back to candidate CRS is unknown; use broad read for candidates.
    cands=candidate_files(year)
    print(f"\n{year}: historiska geometri-kandidater={len(cands)}")
    hist=None; used=None
    for p in cands[:20]:
        g=read_hist_candidate(p,year,None)
        if g is None or g.empty: continue
        # Must look like field polygons.
        if not any("skifte" in norm(c) or "block" in norm(c) for c in g.columns):
            continue
        hist=g.to_crs(3006)
        used=p
        break
    if hist is None:
        source_rows.append({"year":year,"source":"","status":"NOT_FOUND",
                            "candidates":" | ".join(str(x) for x in cands[:10])})
        print(f"  Ingen historisk skiftesgeometri hittades automatiskt för {year}.")
        continue
    source_rows.append({"year":year,"source":str(used),"status":"OK","candidates":len(cands)})
    print(f"  använder: {used}")

    # Relevant attribute columns from historical layer.
    attrs=[]
    for c in hist.columns:
        if c=="geometry": continue
        n=norm(c)
        if any(t in n for t in ("block","skifte","gro","crop","kod","areal","area","arslager","year")):
            attrs.append(c)
    attrs=attrs[:16]
    hs=hist.sindex
    for _,case in case_y.iterrows():
        cg=cur_y[cur_y["field_id"]==case["field_id"]]
        if cg.empty: continue
        cg=cg.iloc[0].geometry
        current_area=float(cg.area)
        idx=list(hs.query(cg, predicate="intersects"))
        pieces=[]
        for j in idx:
            hr=hist.iloc[j]
            inter=cg.intersection(hr.geometry)
            a=float(inter.area) if not inter.is_empty else 0.0
            if a<=1.0: continue
            pieces.append((j,hr,a))
        pieces.sort(key=lambda z:z[2], reverse=True)

        plat,plon=case["pano_lat"],case["pano_lon"]
        pano_m=None
        if pd.notna(plat) and pd.notna(plon):
            pano_m=gpd.GeoSeries(gpd.points_from_xy([plon],[plat]),crs=4326).to_crs(3006).iloc[0]

        for rank,(j,hr,a) in enumerate(pieces[:8],1):
            rec={
                "case_id":case["case_id"],"municipality":case["municipality"],"year":year,
                "field_id":case["field_id"],"akerMinne_crop":case["crop"],
                "hist_rank":rank,
                "overlap_ha":a/10000.0,
                "share_of_current_pct":100*a/current_area if current_area else math.nan,
                "hist_polygon_area_ha":float(hr.geometry.area)/10000.0,
                "share_of_hist_pct":100*a/float(hr.geometry.area) if hr.geometry.area else math.nan,
                "distance_pano_to_hist_polygon_m":float(pano_m.distance(hr.geometry)) if pano_m is not None else math.nan,
                "hist_source":str(used),
            }
            for c in attrs:
                try: rec[c]=hr[c]
                except Exception: pass
            geometry_rows.append(rec)

pd.DataFrame(source_rows).to_csv(OUT/"historical_geometry_sources.csv",index=False,encoding="utf-8-sig")
geo=pd.DataFrame(geometry_rows)
if not geo.empty:
    geo.to_csv(OUT/"historical_overlap_by_case.csv",index=False,encoding="utf-8-sig")

    # Compact case summary, our key falsification test.
    summary=[]
    for _,case in truth.iterrows():
        q=geo[geo["case_id"]==case["case_id"]].sort_values("share_of_current_pct",ascending=False)
        if q.empty:
            summary.append({"case_id":case["case_id"],"year":case["year"],"crop":case["crop"],
                            "status":"NO_HIST_GEOM"})
            continue
        shares=q["share_of_current_pct"].tolist()
        top=shares[0]
        second=shares[1] if len(shares)>1 else 0.0
        total=sum(shares)
        # Strict 1:1 for future validation: almost all current field covered by one historical polygon.
        stable=(top>=95.0 and second<=3.0 and total>=95.0)
        nearest=q.sort_values("distance_pano_to_hist_polygon_m").iloc[0]
        summary.append({
            "case_id":case["case_id"],"municipality":case["municipality"],"year":int(case["year"]),
            "field_id":case["field_id"],"akerMinne_crop":case["crop"],
            "n_hist_overlaps":len(q),"top_share_pct":top,"second_share_pct":second,
            "sum_share_pct":total,"strict_1to1_95pct":stable,
            "nearest_hist_rank_to_pano":int(nearest["hist_rank"]),
            "nearest_pano_dist_m":nearest["distance_pano_to_hist_polygon_m"],
        })
    sm=pd.DataFrame(summary)
    sm.to_csv(OUT/"case_geometry_summary.csv",index=False,encoding="utf-8-sig")
    print("\n=== KOMPAKT GEOMETRIDIAGNOS ===")
    cols=["case_id","year","akerMinne_crop","n_hist_overlaps","top_share_pct","second_share_pct","strict_1to1_95pct","nearest_hist_rank_to_pano","nearest_pano_dist_m"]
    print(sm[cols].to_string(index=False, formatters={
        "top_share_pct":lambda x:f"{x:.1f}" if pd.notna(x) else "",
        "second_share_pct":lambda x:f"{x:.1f}" if pd.notna(x) else "",
        "nearest_pano_dist_m":lambda x:f"{x:.1f}" if pd.notna(x) else "",
    }))
    print(f"\nStrikt 1:1 >=95%: {int(sm['strict_1to1_95pct'].fillna(False).sum())}/{len(sm)} fall")
else:
    print("\nIngen historisk geometri kunde kopplas automatiskt. Intern ÅkerMinne-diagnos är ändå sparad.")

# ---------- D. Special focus SV01/SV03 ----------
focus=truth[truth["case_id"].isin(["SV01","SV03"])]
print("\n=== SV01 / SV03 ===")
for _,c in focus.iterrows():
    print(f"{c.case_id}: {c.municipality} {int(c.year)} field={c.field_id} ÅkerMinne={c.crop} pano={c.meta_date}")
    if not geo.empty:
        q=geo[geo["case_id"]==c.case_id].sort_values("share_of_current_pct",ascending=False)
        for _,r in q.head(5).iterrows():
            extra=[]
            for col in q.columns:
                n=norm(col)
                if col in ("case_id","municipality","year","field_id","akerMinne_crop","hist_rank","overlap_ha","share_of_current_pct","hist_polygon_area_ha","share_of_hist_pct","distance_pano_to_hist_polygon_m","hist_source"):
                    continue
                if any(t in n for t in ("gro","crop","kod","block","skifte")) and pd.notna(r.get(col)):
                    extra.append(f"{col}={r.get(col)}")
            print(f"  hist#{int(r.hist_rank)} overlap={r.share_of_current_pct:.1f}% pano_dist={r.distance_pano_to_hist_polygon_m:.1f}m " + " ".join(extra[:6]))

print(f"\nKLART. Diagnos sparad i: {OUT}")
print("Klistra gärna in sektionen 'KOMPAKT GEOMETRIDIAGNOS' + 'SV01 / SV03' i ChatGPT.")
